stages:
- build
- documentation
- deploy

################################################################################
# Linux / gcc
################################################################################
linux_quick_build:
  except:
    - master@agrumery/aGrUM
    - web
  image: malichief/ubuntu
  tags:
    - docker
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - if ! python3 act --no-fun lib release aGrUM --python=3 -j 4; then python3 act clean && python3 act --no-fun lib release aGrUM --python=3 -j 4; fi
    - python3 act --no-fun test release aGrUM --python=3 -j 4
    - python3 act --no-fun test release pyAgrum --python=3 -t quick -j 4
  retry: 2

linux_build:
  image: malichief/ubuntu
  only:
    - master@agrumery/aGrUM
    - web
  tags:
    - docker
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - if ! python3 act --no-fun lib release aGrUM --python=3 -j 4; then python3 act clean && python3 act --no-fun lib release aGrUM --python=3 -j 4; fi
    - python3 act --no-fun test release aGrUM --python=3 -j 4
    - python3 act --no-fun test release pyAgrum --python=3 -t quick -j 4
  retry: 2

################################################################################
# MacOS / clang
################################################################################
macos_build:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
  tags:
    - macos
    - conda
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
  stage: build
  cache:
    key: macos
    paths:
      - build/
  script:
    - source activate py37
    - if ! python3 act --no-fun lib release aGrUM --python=3 -j 3; then python3 act clean && python3 act --no-fun lib release aGrUM --python=3 -j 3; fi
    - python act --no-fun test release aGrUM --python=3 -j 3
    - python act --no-fun test release pyAgrum --python=3 -t quick -j 3
    - source deactivate
  retry: 2

################################################################################
# Windows / MVSC
################################################################################
windows_build:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\Program Files\\Git\\bin;C:\\ProgramData\\Anaconda3\\envs\\py37;C:\\ProgramData\\Anaconda3\\envs\\py37\\Library\\bin;C:\\ProgramData\\Anaconda3\\envs\\py37\\Scripts;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;%PATH%;"
    ACT_OPTIONS: ""
  cache:
    key: mvsc
    paths:
      - build/
  stage: build
  script:
    - python act clean
    - python act --no-fun test release aGrUM --no-fun --mvsc -d build -j 3
    - python act --no-fun test release pyAgrum --no-fun --mvsc -d build -j 3 -t quick
  retry: 2
