cache:
  untracked: true

################################################################################
# TEMPLATES
################################################################################

.gcc-5: &gcc-5
  tags:
    - linux
    - gcc-5
  variables:
    CC: "/usr/bin/gcc-5"
    CXX: "/usr/bin/g++-5"

.clang-3_8: &clang-3_8
  tags:
    - linux
    - clang
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
    
.clang-llvm-8_0: &clang-llvm-8_0
  tags:
    - macos
    - clang
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"

.mvsc: &mvsc
  tags:
    - windows
    - anaconda
  variables:
    PATH: "C:\\Program Files\\Git\\bin;C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;%PATH%;"
    ACT_OPTIONS: "--mvsc -m BASE+BN+FMDP+ID+LEARNING+PRM -d build"

.agrum_sh: &agrum_sh
  script:
    - python act --no-fun lib release aGrUM $ACT_OPTIONS || python act --no-fun clean && python act --no-fun test release aGrUM $ACT_OPTIONS

.pyagrum_sh: &pyagrum_sh
  script:  
    - python act --no-fun lib release pyAgrum $ACT_OPTIONS || python act --no-fun clean && python act --no-fun test release pyAgrum $ACT_OPTIONS

.agrum_cmd: &agrum_cmd
  script:
    - python act --no-fun test release aGrUM -d build %ACT_OPTIONS% || python act --no-fun clean && python act --no-fun test release aGrUM %ACT_OPTIONS%

.pyagrum_cmd: &pyagrum_cmd
  script:  
    - python act --no-fun test release pyAgrum -d build %ACT_OPTIONS% || python act --no-fun clean && python act --no-fun test release pyAgrum %ACT_OPTIONS%

################################################################################
# BUILD JOBS
################################################################################
.aGrUM_build_template: &aGrUM_build_template
  except:
    - /^doc\/.*$/
    - /^pyagrum/.*$/
  only:
    - branches@agrumery/aGrUM
  stage: build

.pyAgrum_build_template: &pyAgrum_build_template
  except:
    - /^doc\/.*$/
  only:
    - branches@agrumery/aGrUM
  stage: build

linux_gcc-5_agrum:
  <<: *aGrUM_build_template
  <<: *gcc-5
  <<: *agrum_sh

linux_gcc-5_pyagrum:
  <<: *pyAgrum_build_template
  <<: *gcc-5
  <<: *pyagrum_sh

################################################################################
# TEST JOBS
################################################################################
.aGrUM_test_template: &aGrUM_test_template
  except:
    - /^doc\/.*$/
    - /^pyagrum/.*$/
  only:
    - branches@agrumery/aGrUM
  stage: test

.pyAgrum_test_template: &pyAgrum_test_template
  except:
    - /^doc\/.*$/
  only:
    - branches@agrumery/aGrUM
  stage: test

linux_clang_agrum:
  <<: *aGrUM_test_template
  <<: *clang-3_8
  <<: *agrum_sh

linux_clang_pyagrum:
  <<: *pyAgrum_test_template
  <<: *clang-3_8
  <<: *pyagrum_sh

windows_mvsc_agrum:
  <<: *aGrUM_test_template
  <<: *mvsc
  <<: *agrum_cmd

windows_mvsc_pyagrum:
  <<: *pyAgrum_test_template
  <<: *mvsc
  <<: *pyagrum_cmd

macos_clang_agrum:
  <<: *aGrUM_test_template
  <<: *clang-llvm-8_0
  <<: *agrum_sh
  
macos_clang_pyagrum:
  <<: *pyAgrum_test_template
  <<: *clang-llvm-8_0
  <<: *pyagrum_sh
  
################################################################################
# DEPLOY JOBS
################################################################################

