linux_gcc-5_release:
  tags:
    - linux
  stage: build
  variables:
    CC: "/usr/bin/gcc-5"
    CXX: "/usr/bin/g++-5"
  script: 
    - python act --no-fun lib release
  cache:
    untracked: true

linux_gcc-4.9_release:
  tags:
    - linux
  stage: build
  variables:
    CC: "/usr/bin/gcc-4.9"
    CXX: "/usr/bin/g++-4.9"
  script: 
    - python act --no-fun lib release
  cache:
    untracked: true
