linux_gcc-5_release:
  tags:
    - linux
  stage: build
  variables:
    CC: "/usr/bin/gcc-5"
    CXX: "/usr/bin/g++-5"
  before_script: 
    - apt update && apt -y install g++-5 cmake python
  script: 
    - python act lib release
  artifacts:
    paths:
      - build/
