stages:
- build
- deploy

################################################################################
# Linux / gcc
################################################################################
linux_agrum:
  image: malichief/ubuntu
  tags:
    - docker
    - linux
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - python3 act clean
    - python3 act --no-fun test release aGrUM --python=3 -j halfexcept1
  retry: 2

linux_pyagrum:
  image: malichief/ubuntu
  tags:
    - docker
    - linux
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - python3 act clean
    - python3 act --no-fun test release pyAgrum --python=3 -j halfexcept1 -t quick
  retry: 2
  
################################################################################
# Linux / gcc merge requests
################################################################################
linux_agrum_merge_requests:
  image: malichief/ubuntu
  only:
    - merge_requests
  tags:
    - docker
    - linux
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - python3 act clean
    - python3 act --no-fun test release aGrUM --python=3 -j halfexcept1
  retry: 2

linux_pyagrum_merge_requests:
  only:
    - merge_requests
  image: malichief/ubuntu
  tags:
    - docker
    - linux
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - python3 act clean
    - python3 act --no-fun test release pyAgrum --python=3 -j halfexcept1 -t quick
  retry: 2

################################################################################
# MacOS / clang
################################################################################
macos_agrum:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
    - merge_requests
  tags:
    - macos
    - conda
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
  stage: build
  cache:
    key: macos
    paths:
      - build/
  script:
    - . /Users/agrum/miniconda3/etc/profile.d/conda.sh
    - conda activate py37
    - python act clean
    - python act --no-fun test release aGrUM --python=3 -j halfexcept1
    - conda deactivate
  retry: 2

macos_pyagrum:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
    - merge_requests
  tags:
    - macos
    - conda
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
  stage: build
  cache:
    key: macos
    paths:
      - build/
  script:
    - . /Users/agrum/miniconda3/etc/profile.d/conda.sh
    - conda activate py37
    - python act clean
    - python act --no-fun test release pyAgrum --python=3 -t quick -j halfexcept1
    - conda deactivate
  retry: 2

################################################################################
# Windows / MVSC
################################################################################
windows_agrum_2015:
  only:
   - master@agrumery/aGrUM
   - web@agrumery/aGrUM
   - merge_requests
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\ProgramData\\Anaconda3\\Scripts;C:\\ProgramData\\Anaconda3;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\dotnet\\;C:\\Users\\aGrUM\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64;"
  cache:
    key: mvsc
    paths:
      - build/
  stage: build
  script:
    - conda create -n "gitlab-ci-%CI_JOB_ID%" python=3.7
    - call activate "gitlab-ci-%CI_JOB_ID%"
    - conda install -y numpy nbformat nbconvert jupyter matplotlib pydotplus pandas scipy cmake
    - python act clean
    - python act --no-fun --mvsc -d build -j halfexcept1 test release aGrUM 
    - call activate py37
    - deactivate
    - conda remove -n "gitlab-ci-%CI_JOB_ID%" --all --force -y
  retry: 2

windows_pyagrum_2015:
  only:
   - master@agrumery/aGrUM
   - web@agrumery/aGrUM
   - merge_requests
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\ProgramData\\Anaconda3\\Scripts;C:\\ProgramData\\Anaconda3;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\dotnet\\;C:\\Users\\aGrUM\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64;"
  cache:
    key: mvsc
    paths:
      - build/
  stage: build
  script:
    - conda create -n "gitlab-ci-%CI_JOB_ID%" python=3.7
    - call activate "gitlab-ci-%CI_JOB_ID%"
    - conda install -y numpy nbformat nbconvert jupyter matplotlib pydotplus pandas scipy cmake
    - python act clean
    - python act --no-fun test release pyAgrum --no-fun --mvsc -d build -j halfexcept1 -t quick
    - call activate py37
    - conda remove -n "gitlab-ci-%CI_JOB_ID%" --all --force -y
  retry: 2

windows_agrum_2017:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
    - merge_requests
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\ProgramData\\Anaconda3\\Scripts;C:\\ProgramData\\Anaconda3;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\Bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\dotnet\\;C:\\Users\\aGrUM\\AppData\\Local\\Microsoft\\WindowsApps;"
  cache:
    key: mvsc17
    paths:
      - build/
  stage: build
  script:
    - conda create -n "gitlab-ci-%CI_JOB_ID%" python=3.7
    - call activate "gitlab-ci-%CI_JOB_ID%"
    - conda install -y numpy nbformat nbconvert jupyter matplotlib pydotplus pandas scipy cmake
    - python act clean
    - python act --no-fun test release aGrUM --no-fun --mvsc17 -d build -j halfexcept1
    - call activate py37
    - conda remove -n "gitlab-ci-%CI_JOB_ID%" --all --force -y
  retry: 2

windows_pyagrum_2017:
  only:
   - master@agrumery/aGrUM
   - web@agrumery/aGrUM
   - merge_requests
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\ProgramData\\Anaconda3\\Scripts;C:\\ProgramData\\Anaconda3;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\Bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\dotnet\\;C:\\Users\\aGrUM\\AppData\\Local\\Microsoft\\WindowsApps;"
  cache:
    key: mvsc17
    paths:
      - build/
  stage: build
  script:
    - conda create -n "gitlab-ci-%CI_JOB_ID%" python=3.7
    - call activate "gitlab-ci-%CI_JOB_ID%"
    - conda install -y numpy nbformat nbconvert jupyter matplotlib pydotplus pandas scipy cmake
    - python act clean
    - python act --no-fun test release pyAgrum --no-fun --mvsc17 -d build -j halfexcept1 -t quick
    - call activate py37
    - conda remove -n "gitlab-ci-%CI_JOB_ID%" --all --force -y
  retry: 2

################################################################################
# Deploy  wheels
################################################################################
linux_build:
  image: malichief/ubuntu
  only:
    - tags@agrumery/aGrUM
  tags:
    - docker
    - linux
  cache:
    key: linux
    paths:
      - build/
  stage: deploy
  script:
    - apt-get install -y curl
    - curl -X POST -F token=${AGRUM_DEPLOY_TOKEN} -F ref=master -F "variables[AGRUM_TAG]=${CI_COMMIT_TAG}" -F "variables[AGRUM_BUILD]=1" -F "variables[DEPLOY_TO_PYPI]=TRUE" -F "variables[DEPLOY_DOC]=TRUE"  https://gitlab.com/api/v4/projects/4935470/trigger/pipeline
  retry: 1
