cache:
  untracked: false

################################################################################
# TEST
################################################################################

linux_gcc-5_release:
  tags:
    - linux
    - gcc-5
  stage: test
  variables:
    CC: "/usr/bin/gcc-5"
    CXX: "/usr/bin/g++-5"
  script: 
    - python act --no-fun clean 
    - python act --no-fun test release aGrUM

