stages:
- build
- deploy

################################################################################
# Linux / gcc
################################################################################
linux_agrum:
  image: malichief/ubuntu
  tags:
    - docker
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - if ! python3 act --no-fun test release aGrUM --python=3 -j 4; then python3 act clean && python3 act --no-fun test release aGrUM --python=3 -j 4; fi
  retry: 2

linux_pyagrum:
  image: malichief/ubuntu
  tags:
    - docker
  cache:
    key: linux
    paths:
      - build/
  stage: build
  script:
    - if ! python3 act --no-fun test release pyAgrum --python=3 -j 4 -t quick; then python3 act clean && python3 act --no-fun test release pyAgrum --python=3 -j 4 -t quick; fi
  retry: 2

################################################################################
# MacOS / clang
################################################################################
macos_agrum:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
  tags:
    - macos
    - conda
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
  stage: build
  cache:
    key: macos
    paths:
      - build/
  script:
    - . /Users/agrum/miniconda3/etc/profile.d/conda.sh
    - conda activate py37
    - if ! python3 act --no-fun lib release aGrUM --python=3 -j 3; then python3 act clean && python3 act --no-fun lib release aGrUM --python=3 -j 3; fi
    - python act --no-fun test release aGrUM --python=3 -j 3
    - conda deactivate
  retry: 2

macos_pyagrum:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
  tags:
    - macos
    - conda
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
  stage: build
  cache:
    key: macos
    paths:
      - build/
  script:
    - . /Users/agrum/miniconda3/etc/profile.d/conda.sh
    - conda activate py37
    - if ! python3 act --no-fun lib release aGrUM --python=3 -j 3; then python3 act clean && python3 act --no-fun lib release aGrUM --python=3 -j 3; fi
    - python act --no-fun test release pyAgrum --python=3 -t quick -j 3
    - conda deactivate
  retry: 2

################################################################################
# Windows / MVSC
################################################################################
windows_agrum:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\Program Files\\Git\\bin;C:\\ProgramData\\Anaconda3\\envs\\py37;C:\\ProgramData\\Anaconda3\\envs\\py37\\Library\\bin;C:\\ProgramData\\Anaconda3\\envs\\py37\\Scripts;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;%PATH%;"
    ACT_OPTIONS: ""
  cache:
    key: mvsc
    paths:
      - build/
  stage: build
  script:
    - python act clean
    - python act --no-fun test release aGrUM --no-fun --mvsc -d build -j 3
  retry: 2

windows_pyagrum:
  only:
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
  tags:
    - windows
    - conda
  variables:
    PATH: "C:\\Program Files\\Git\\bin;C:\\ProgramData\\Anaconda3\\envs\\py37;C:\\ProgramData\\Anaconda3\\envs\\py37\\Library\\bin;C:\\ProgramData\\Anaconda3\\envs\\py37\\Scripts;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;%PATH%;"
    ACT_OPTIONS: ""
  cache:
    key: mvsc
    paths:
      - build/
  stage: build
  script:
    - python act clean
    - python act --no-fun test release pyAgrum --no-fun --mvsc -d build -j 3 -t quick
  retry: 2

################################################################################
# Deploy  wheels
################################################################################
linux_build:
  image: malichief/ubuntu
  only:
    - tags@agrumery/aGrUM
  tags:
    - docker
  cache:
    key: linux
    paths:
      - build/
  stage: deploy
  script:
    - apt-get install -y curl
    - curl -X POST -F token=${AGRUM_DEPLOY_TOKEN} -F ref=master -F "variables[AGRUM_TAG]=${CI_COMMIT_TAG}" -F "variables[AGRUM_BUILD]=1" -F "variables[DEPLOY_TO_PYPI]=TRUE" -F "variables[DEPLOY_DOC]=TRUE"  https://gitlab.com/api/v4/projects/4935470/trigger/pipeline
  retry: 1