variables:
  LINUX_64_IMAGE: "agrumery/manylinux_2_28_x86_64"
  BUILD_DOC: "wrappers/pyAgrum/wheelhouse/build_doc.sh"
  LINUX_BUILD: "wrappers/pyAgrum/wheelhouse/build_linux.sh"
  LINUX_WHEELHOUSE: "wrappers/pyAgrum/wheelhouse/build_wheels_linux.sh"
  LINUX_NIGHTLY_WHEELHOUSE: "wrappers/pyAgrum/wheelhouse/build_nightly_wheels_linux.sh"
  OSX_BUILD: "wrappers/pyAgrum/wheelhouse/build_macos.sh"
  OSX_WHEELHOUSE: "wrappers/pyAgrum/wheelhouse/build_wheels_macos.sh"
  WINDOWS_BUILD: "wrappers/pyAgrum/wheelhouse/build_windows.ps1"
  WINDOWS_WHEELHOUSE: "wrappers/pyAgrum/wheelhouse/build_wheels_windows.ps1"

stages:
  - build
  - deploy

.common_artifacts: &common_artifacts
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_success
    expire_in: 1 week
    paths:
      - wheels/*.whl

################################################################################
#                              TEMPLATES                                       #
################################################################################

.build_template: &build_template
  stage: build
  retry: 1

.linux_build_template: &linux_build_template
  <<: *build_template
  tags:
    - docker
    - linux
    - manylinux1

.linux_wheel_template: &linux_wheel_template
  <<: *common_artifacts
  <<: *build_template
  only:
    - tags
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
    - merge_requests
  image: $LINUX_64_IMAGE
  tags:
    - docker
    - linux
    - triskele

.macos_build_template: &macos_build_template
  <<: *common_artifacts
  <<: *build_template
  only:
    - tags
    - web@agrumery/aGrUM
    - master@agrumery/aGrUM
    - merge_requests
  tags:
    - macos
    - conda
  cache:
    key: macos
    paths:
      - build/

.windows_build_template: &windows_build_template
  <<: *common_artifacts
  <<: *build_template
  only:
    - tags
    - master@agrumery/aGrUM
    - web@agrumery/aGrUM
    - merge_requests
  tags:
    - windows
    - conda
    - agrumerie2-powershell
  cache:
    key: mvsc
    paths:
      - build/

################################################################################
#                                SCRIPTS                                       #
################################################################################

.windows_wheel_script: &windows_wheel_script
  - powershell -File $WINDOWS_WHEELHOUSE -CI_JOB_ID $CI_JOB_ID -CI_PROJECT_DIR $CI_PROJECT_DIR -PYTHON_VERSION $PYTHON_VERSION

.windows_build_script: &windows_build_script
  - powershell -File $WINDOWS_BUILD -CI_JOB_ID $CI_JOB_ID -CI_PROJECT_DIR $CI_PROJECT_DIR -PYTHON_VERSION $PYTHON_VERSION -TARGET $TARGET -COMPILER $COMPILER

################################################################################
#                               ON PUSH                                        #
################################################################################

################################################################################
# Linux / gcc
################################################################################

linux_agrum:
  <<: *linux_build_template
  image: agrumery/ubuntu_py312
  script:
    - bash $LINUX_BUILD aGrUM

linux_pyagrum_py38:
  <<: *linux_build_template
  image: agrumery/ubuntu_py38
  script:
    - bash $LINUX_BUILD pyAgrum

linux_pyagrum_py312:
  <<: *linux_build_template
  image: agrumery/ubuntu_py312
  script:
    - bash $LINUX_BUILD pyAgrum

################################################################################
#                        ON MERGE, MASTER AND TAGS                             #
################################################################################

################################################################################
#                                 WHEELS                                       #
################################################################################

################################################################################
# Linux x86_64 / gcc
################################################################################

build_wheel_linux_py38:
  <<: *linux_wheel_template
  script:
    - bash $LINUX_WHEELHOUSE cp38-cp38

build_wheel_linux_py312:
  <<: *linux_wheel_template
  script:
    - bash $LINUX_WHEELHOUSE cp312-cp312

build_nightly_wheel_linux_py312:
  <<: *linux_wheel_template
  script:
    - bash $LINUX_NIGHTLY_WHEELHOUSE cp312-cp312

################################################################################
# MacOS
################################################################################

build_wheel_osx_py38:
  <<: *macos_build_template
  script:
    - bash $OSX_WHEELHOUSE py38

build_wheel_osx_py312:
  <<: *macos_build_template
  script:
    - bash $OSX_WHEELHOUSE py312

################################################################################
# Windows / MVSC
################################################################################

build_wheel_windows_py38:
  <<: *windows_build_template
  variables:
    PATH: $PATH_64_MVSC22_AGRUMERIE2
    PYTHON_VERSION: "3.8"
  script:
    - *windows_wheel_script

build_wheel_windows_py312:
  <<: *windows_build_template
  variables:
    PATH: $PATH_64_MVSC22_AGRUMERIE2
    PYTHON_VERSION: "3.12"
  script:
    - *windows_wheel_script

################################################################################
#                                 BUILD                                        #
################################################################################

################################################################################
# MacOS / clang
################################################################################

macos_agrum:
  <<: *macos_build_template
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
    PYTHON_VERSION: "py312"
    TARGET: "aGrUM"
  script:
    - bash $OSX_BUILD $PYTHON_VERSION $TARGET

macos_pyagrum:
  <<: *macos_build_template
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
    PYTHON_VERSION: "py312"
    TARGET: "pyAgrum"
  script:
    - bash $OSX_BUILD $PYTHON_VERSION $TARGET

################################################################################
# Windows / MVSC
################################################################################

windows_agrum_2019:
  <<: *windows_build_template
  variables:
    PATH: $PATH_64_MVSC19_AGRUMERIE2
    PYTHON_VERSION: "3.8"
    TARGET: "aGrUM"
    COMPILER: "mvsc19"
  script:
    - *windows_build_script

windows_agrum_2022:  
  <<: *windows_build_template
  variables:
    PATH: $PATH_64_MVSC22_AGRUMERIE2
    PYTHON_VERSION: "3.8"
    TARGET: "aGrUM"
    COMPILER: "mvsc22"
  script:
    - *windows_build_script

windows_pyagrum_2022:  
  <<: *windows_build_template
  variables:
    PATH: $PATH_64_MVSC22_AGRUMERIE2
    PYTHON_VERSION: "3.12"
    TARGET: "pyAgrum"
    COMPILER: "mvsc22"
  script:
    - *windows_build_script

################################################################################
# Windows / MINGW
################################################################################

windows_pyagrum_mingw:  
  <<: *windows_build_template
  variables:
    PATH: $PATH_64_MINGW_AGRUMERIE2
    PYTHON_VERSION: "3.12"
    TARGET: "pyAgrum"
    COMPILER: "mingw64"
  script:
    - *windows_build_script

################################################################################
# Deploy  wheels
################################################################################

linux_build:
  image: agrumery/ubuntu
  only:
    - tags@agrumery/aGrUM
  tags:
    - docker
    - linux
  cache:
    key: linux
    paths:
      - build/
  stage: deploy
  script:
    - apt-get install -y curl
    - curl -X POST -F token=${AGRUM_DEPLOY_TOKEN} -F ref=master -F "variables[AGRUM_TAG]=${CI_COMMIT_TAG}" -F "variables[AGRUM_BUILD]=1" -F "variables[DEPLOY_TO_PYPI]=TRUE" -F "variables[DEPLOY_DOC]=TRUE"  https://gitlab.com/api/v4/projects/4935470/trigger/pipeline
  retry: 1

################################################################################
#                                  RTD                                         #
################################################################################

build_doc:
  <<: *linux_wheel_template
  image: agrumery/ubuntu_py38
  script:
    - bash $BUILD_DOC