# Support Python 3.10+.
target-version = "py310"

line-length = 120
indent-width = 2

# Include notebooks in formatting/linting
extend-include = ["*.ipynb"]

exclude = [
  "**/testunits/generateTestExec.py",
  '**/apps/*',
  '**/notebooks-archives/*',
  '**/generated-files/*',
  "**/Untitled*.ipynb",
  "wrappers/pyagrum/cmake/*",
] # Skip certain notebooks

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint]
#extend-select = ["E501"]
# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]


# E741 : ambiguous variable name (e.g. "l", "O", "I").
ignore = ["E741"]

[lint.pydocstyle]
convention = "numpy"
